### ISSUE TITLE
liên lạc với bạn bằng cách nào

### ISSUE THREAD

**Issue by ghost** [aujiz11/NGG-open.mp#3]
Mình cần hỏi kinh nghiệm và trao đổi riêng được chứ ?

**Comment by snesgoku** [comment]
discord : #mintpun

**Comment by aujiz11** [comment]
#aujiz1

**Comment by Fvg12** [comment]
Create English version

**Comment by aujiz11** [comment]
> Quote reply

I did not do the conversion for English!
